import tomcat-7.0.69-10.el7

diff --git a/SOURCES/tomcat-functions b/SOURCES/tomcat-functions
--- a/SOURCES/tomcat-functions
+++ b/SOURCES/tomcat-functions
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 if [ -r /usr/share/java-utils/java-functions ]; then
-  . /usr/share/java-utils/java-functions
+    . /usr/share/java-utils/java-functions
 else
-  echo "Can't read Java functions library, aborting"
-  exit 1
+    echo "Can't read Java functions library, aborting"
+    exit 1
 fi
 
 _save_function() {
@@ -15,28 +15,27 @@ _save_function() {
 
 run_jsvc(){
     if [ -x /usr/bin/jsvc ]; then
-	TOMCAT_USER="tomcat"
-       	JSVC="/usr/bin/jsvc"
+        TOMCAT_USER="${TOMCAT_USER:-tomcat}"
+        JSVC="/usr/bin/jsvc"
 	
-	JSVC_OPTS="-nodetach -pidfile /var/run/jsvc-tomcat${NAME}.pid -user ${TOMCAT_USER} -outfile ${CATALINA_BASE}/logs/catalina.out -errfile ${CATALINA_BASE}/logs/catalina.out"
-	if [ "$1" = "stop" ]; then
-		JSVC_OPTS="${JSVC_OPTS} -stop"
-    	fi
+        JSVC_OPTS="-nodetach -pidfile /var/run/jsvc-tomcat${NAME}.pid -user ${TOMCAT_USER} -outfile ${CATALINA_BASE}/logs/catalina.out -errfile ${CATALINA_BASE}/logs/catalina.out"
+        if [ "$1" = "stop" ]; then
+            JSVC_OPTS="${JSVC_OPTS} -stop"
+        fi
 
         exec "${JSVC}" ${JSVC_OPTS} ${FLAGS} -classpath "${CLASSPATH}" ${OPTIONS} "${MAIN_CLASS}" "${@}"
     else
        	echo "Can't find /usr/bin/jsvc executable"
     fi
-
 }
 
 _save_function run run_java
 
 run() {
-   if [ "${USE_JSVC}" = "true" ] ; then
-	run_jsvc $@
-   else
-	run_java $@
-   fi
+    if [ "${USE_JSVC}" = "true" ] ; then
+        run_jsvc $@
+    else
+        run_java $@
+    fi
 }
 
